// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterHeaterTest.Models
{
    public partial class AktVodootpornostKotao
    {
        public int Id { get; set; }
        public int IdSerijskiBrojKotao { get; set; }
        /// <summary>
        /// 0-neispravan, 1-ispravan
        /// </summary>
        public bool Ispravan { get; set; }
        public int? IdVrstaProblemaOpis { get; set; }
        public DateTime DatumKontrolisanja { get; set; }
        public string IdKorisnikKontrolisao { get; set; }

        public virtual SifSerijskiBrojKotao IdSerijskiBrojKotaoNavigation { get; set; }
        public virtual AgrVrstaProblemaOpis IdVrstaProblemaOpisNavigation { get; set; }
    }
}