// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterHeaterTest.Models
{
    public partial class SifArtikal
    {
        public int Id { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public int IdPc { get; set; }
        public int IdKlasa { get; set; }
        public DateTime DatumKreiran { get; set; }
    }
}