// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterHeaterTest.Models
{
    public partial class SifSerijskiBrojKotao
    {
        public SifSerijskiBrojKotao()
        {
            AktVodootpornostKotao = new HashSet<AktVodootpornostKotao>();
        }

        public int Id { get; set; }
        public int IdAgrSifraKotaoSarzaKotao { get; set; }
        public string RedniBroj { get; set; }
        public DateTime DatumKreiranja { get; set; }

        public virtual AgrSifraKotaoSarzaKotao IdAgrSifraKotaoSarzaKotaoNavigation { get; set; }
        public virtual ICollection<AktVodootpornostKotao> AktVodootpornostKotao { get; set; }
    }
}