// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterHeaterTest.Models
{
    public partial class SifVrstaProblema
    {
        public SifVrstaProblema()
        {
            AgrVrstaProblemaOpis = new HashSet<AgrVrstaProblemaOpis>();
        }

        public int Id { get; set; }
        public string Naziv { get; set; }
        public DateTime DatumKreiranja { get; set; }
        public string IdKorisnikKreirao { get; set; }

        public virtual ICollection<AgrVrstaProblemaOpis> AgrVrstaProblemaOpis { get; set; }
    }
}